language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
solution: NugetVisualizer.sln

before_install: 
 - cd NugetVisualizer
 - chmod +x createConfig.sh
 - chmod +x test.sh
 
 after_deploy:
 - ./test.sh $TRAVIS_BUILD_DIR

script:
 - dotnet restore
 - ./createConfig.sh $GITHUB_TOKEN
 - dotnet build NugetVisualizer.sln
 - dotnet test UnitTests