language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
solution: NugetVisualizer.sln

before_install: 
 - cd NugetVisualizer
 - chmod +x createConfig.sh
 
 after_deploy:
 - cd $TRAVIS_BUILD_DIR
 - find -type d -printf '%d\t%P\n' | sort -r -nk1 | cut -f2-

script:
 - dotnet restore
 - ./createConfig.sh $GITHUB_TOKEN
 - dotnet build NugetVisualizer.sln
 - dotnet test UnitTests