// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using NugetVisualizer.Core.Repositories;
using System;

namespace NugetVisualizer.Core.Migrations
{
    [DbContext(typeof(NugetVisualizerContext))]
    partial class NugetVisualizerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("NugetVisualizer.Core.Domain.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("TargetFramework");

                    b.Property<string>("Version");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Package");
                });

            modelBuilder.Entity("NugetVisualizer.Core.Domain.Project", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Name");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("NugetVisualizer.Core.Domain.Package", b =>
                {
                    b.HasOne("NugetVisualizer.Core.Domain.Project")
                        .WithMany("Packages")
                        .HasForeignKey("Name");
                });
#pragma warning restore 612, 618
        }
    }
}
